### ISSUE TITLE
Unable to compile with flash-attn

### ISSUE THREAD

**Issue by uglyoldbob** [huggingface/candle#2360]
I am currently unable to compile with features flash-attn on ubuntu 22.04.

It looks like the error is related to __grid_constant__ not being defined. However, simply removing the identifier from the source doesn't make it compile either.

```
kernels/flash_fwd_launch_template.h(30): error: incomplete type is not allowed

  kernels/flash_fwd_launch_template.h(30): error: identifier "__grid_constant__" is undefined

  kernels/flash_fwd_launch_template.h(30): error: expected a ")"

  kernels/flash_fwd_launch_template.h(30): error: expected a ";"

  At end of source: error: expected a ";"

  5 errors detected in the compilation of "kernels/flash_fwd_hdim32_fp16_sm80.cu".
  # --error 0x1 --
  thread '<unnamed>' panicked at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen_cuda-0.1.5/src/lib.rs:262:21:
  nvcc error while executing compiling: "nvcc" "--gpu-architecture=sm_87" "-c" "-o" "/home/thomas/temp/bible/rbible/target/release/build/candle-flash-attn-4670c2cfe17d66aa/out/flash_fwd_hdim32_fp16_sm80-3a7585e74a278dc3.o" "--default-stream" "per-thread" "-std=c++17" "-O3" "-U__CUDA_NO_HALF_OPERATORS__" "-U__CUDA_NO_HALF_CONVERSIONS__" "-U__CUDA_NO_HALF2_OPERATORS__" "-U__CUDA_NO_BFLOAT16_CONVERSIONS__" "-Icutlass/include" "--expt-relaxed-constexpr" "--expt-extended-lambda" "--use_fast_math" "--verbose" "kernels/flash_fwd_hdim32_fp16_sm80.cu"
```

With the __grid_constant__ removed from kernels/flash_fwd_launch_template (most likely not the proper solution anyways).
```
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with â...â:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         â_ArgTypesâ
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with â...â:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         â_ArgTypesâ
# --error 0x1 --
```

**Comment by EricLBuehler** [comment]
Hey @uglyoldbob! I think this is an issue with GCC version 11. As you are running Ubuntu, the following should work:

```
sudo apt install gcc-10
export NVCC_CCBIN=/usr/bin/gcc-10
```

I would also recommend adding the `export` line to your `.bashrc`.

**Comment by uglyoldbob** [comment]
> /usr/bin/gcc-10

Ok that seems to solve the second problem. Any ideas on the first problem regarding grid_constant?

**Comment by EricLBuehler** [comment]
@uglyoldbob can you please run:
```
nvcc --version
nvidia-smi --query-gpu=compute_cap --format=csv
```

**Comment by uglyoldbob** [comment]
@EricLBuehler 
nvcc
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```
nvidia-smi
```
compute_cap
8.9
```

I am also using CUDA_COMPUTE_CAP="87" in the env section of .cargo/config.toml

**Comment by EricLBuehler** [comment]
@uglyoldbob can you please run without `CUDA_COMPUTE_CAP="87"` and let me know what happens? 

I think the error is that the `nvcc` version is too old. I would install, for instance, CUDA 12.3:

Install compiler:
```
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-3
```
Symlink it:
```
sudo ln -s /usr/local/cuda-12.3/bin/nvcc /usr/bin/nvcc
```
Add to path:
```
export PATH=/usr/local/cuda-12.3/bin:$PATH
```

I think this may resolve the issue!

**Comment by EricLBuehler** [comment]
Great, glad I could help!
