### ISSUE TITLE
Flash-attn feature fails to build in 22.04 Docker

### ISSUE THREAD

**Issue by sempervictus** [huggingface/candle#3043]
When using `docker.io/nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04` to build Candle, there are several path problems involved such as `libcudnn9-headers-cuda-12` installing headers to `/usr/include/x86_64-linux-gnu` where `cudarc` does not search (easily fixed) and then running into `candle-flash-attn` throwing
```rust
20.02   # stderr
20.02 
20.02   In file included from kernels/flash_fwd_launch_template.h:12,
20.02                    from kernels/flash_fwd_hdim32_fp16_sm80.cu:5:
20.02   kernels/flash_fwd_kernel.h:9:10: fatal error: cute/tensor.hpp: No such file or directory
```
both in the docker and on a native Arch system.

I've been using @EricLBuehler's `candle-vllm` (and `mistralrs`, from where the Dockerfile originated) library quite a bit and _that_ compiles just fine in the same env but their dependencies diverge from this tree

[candle-fail.txt](https://github.com/user-attachments/files/21563697/candle-fail.txt)

**Comment by sempervictus** [comment]
Found it in the readme, adding to dockerfile, apologies
